/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazCita;

import citas.CitaClinicaEntidad;
import citas.CitaEntidad;
import citas.CitaExternaEntidad;
import citasFabrica.FabricaCitas;
import citasFabrica.FabricaCitasInterfaz;
import java.awt.Panel;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JPanel;
import usuarios.DoctorEntidad;
import usuarios.fabrica.FabricaUsuarios;
import usuarios.fabrica.UsuariosFabricaInterfaz;
import usuarios.permisos.PermisosEntidadJpaController;

/**
 *
 * @author Mr josh
 */
public class InterfazPrincipalcitas extends javax.swing.JFrame {
    EntityManagerFactory  emf;

    /**
     * Creates new form InterfazPrincipalcitas
     */
    public InterfazPrincipalcitas() {
        emf = Persistence.createEntityManagerFactory("ClinicasADPU");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        ClinicasADPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ClinicasADPU").createEntityManager();
        citaentidadQuery = java.beans.Beans.isDesignTime() ? null : ClinicasADPUEntityManager.createQuery("SELECT c FROM Citaentidad c");
        citaentidadList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : citaentidadQuery.getResultList();
        panelCreacionCitaProgramada = new javax.swing.JTabbedPane();
        PanelPrincipal = new javax.swing.JPanel();
        botoncrearcitaprogramada = new javax.swing.JButton();
        botoncrearcitaexterna = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        panelCreacionCitaExterna = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campo_cita_externa_observacion = new javax.swing.JTextField();
        campo_cita_externa_paciente = new javax.swing.JTextField();
        campo_cita_externa_especialidad = new javax.swing.JTextField();
        campo_cita_externa_doctor = new javax.swing.JTextField();
        campo_cita_externa_fecha = new javax.swing.JTextField();
        campo_cita_externa_motivo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        campo_cita_programada_observacion = new javax.swing.JTextField();
        campo_cita_programada_paciente = new javax.swing.JTextField();
        campo_cita_programada_especialidad = new javax.swing.JTextField();
        campo_cita_programada_doctor = new javax.swing.JTextField();
        campo_cita_programada_fecha = new javax.swing.JTextField();
        campo_cita_programada_motivo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botoncrearcitaprogramada.setText("Programada");
        botoncrearcitaprogramada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncrearcitaprogramadaActionPerformed(evt);
            }
        });
        PanelPrincipal.add(botoncrearcitaprogramada, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        botoncrearcitaexterna.setText("Externa");
        PanelPrincipal.add(botoncrearcitaexterna, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 101, -1));

        jLabel1.setText("Creacion de cita: click encima para crear el tipo de cita");
        PanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, citaentidadList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fecha}"));
        columnBinding.setColumnName("Fecha");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${secretariaId}"));
        columnBinding.setColumnName("Secretaria Id");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pacienteId}"));
        columnBinding.setColumnName("Paciente Id");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${doctorId}"));
        columnBinding.setColumnName("Doctor Id");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${receta}"));
        columnBinding.setColumnName("Receta");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${razon}"));
        columnBinding.setColumnName("Razon");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precio}"));
        columnBinding.setColumnName("Precio");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dtype}"));
        columnBinding.setColumnName("Dtype");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${direccion}"));
        columnBinding.setColumnName("Direccion");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTable1);

        PanelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 550, 190));

        jLabel2.setText("Listado de citas programadas para hoy.");
        PanelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        panelCreacionCitaProgramada.addTab("Citas", PanelPrincipal);

        panelCreacionCitaExterna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Doctor");
        panelCreacionCitaExterna.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel7.setText("Especialidad");
        panelCreacionCitaExterna.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel8.setText("Motivo");
        panelCreacionCitaExterna.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel9.setText("Fecha");
        panelCreacionCitaExterna.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel10.setText("Paciente");
        panelCreacionCitaExterna.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel11.setText("Observacion");
        panelCreacionCitaExterna.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        panelCreacionCitaExterna.add(campo_cita_externa_observacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 220, 30));
        panelCreacionCitaExterna.add(campo_cita_externa_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 220, 30));
        panelCreacionCitaExterna.add(campo_cita_externa_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 220, 30));
        panelCreacionCitaExterna.add(campo_cita_externa_doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 220, 30));
        panelCreacionCitaExterna.add(campo_cita_externa_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 220, 30));
        panelCreacionCitaExterna.add(campo_cita_externa_motivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 220, 30));

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelCreacionCitaExterna.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        panelCreacionCitaProgramada.addTab("Creacion Cita externa", panelCreacionCitaExterna);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Doctor");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel13.setText("Especialidad");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel14.setText("Motivo");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel15.setText("Fecha");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel16.setText("Paciente");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel17.setText("Observacion");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        jPanel2.add(campo_cita_programada_observacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 220, 30));
        jPanel2.add(campo_cita_programada_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 220, 30));
        jPanel2.add(campo_cita_programada_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 220, 30));
        jPanel2.add(campo_cita_programada_doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 220, 30));
        jPanel2.add(campo_cita_programada_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 220, 30));
        jPanel2.add(campo_cita_programada_motivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 220, 30));

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        panelCreacionCitaProgramada.addTab("Creacion Cita programada", jPanel2);

        getContentPane().add(panelCreacionCitaProgramada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncrearcitaprogramadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncrearcitaprogramadaActionPerformed
        // TODO add your handling code here:
        this.panelCreacionCitaExterna.setVisible(true);
    }//GEN-LAST:event_botoncrearcitaprogramadaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CitaClinicaEntidad cita_nuevo = new CitaClinicaEntidad();
        FabricaCitasInterfaz fabrica_usuarios = new FabricaCitas();
        fabrica_usuarios.crearCita(cita_nuevo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CitaExternaEntidad cita_nuevo = new CitaExternaEntidad();
        FabricaCitasInterfaz fabrica_usuarios = new FabricaCitas();
        fabrica_usuarios.crearCita(cita_nuevo);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipalcitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipalcitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipalcitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipalcitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipalcitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager ClinicasADPUEntityManager;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton botoncrearcitaexterna;
    private javax.swing.JButton botoncrearcitaprogramada;
    private javax.swing.JTextField campo_cita_externa_doctor;
    private javax.swing.JTextField campo_cita_externa_especialidad;
    private javax.swing.JTextField campo_cita_externa_fecha;
    private javax.swing.JTextField campo_cita_externa_motivo;
    private javax.swing.JTextField campo_cita_externa_observacion;
    private javax.swing.JTextField campo_cita_externa_paciente;
    private javax.swing.JTextField campo_cita_programada_doctor;
    private javax.swing.JTextField campo_cita_programada_especialidad;
    private javax.swing.JTextField campo_cita_programada_fecha;
    private javax.swing.JTextField campo_cita_programada_motivo;
    private javax.swing.JTextField campo_cita_programada_observacion;
    private javax.swing.JTextField campo_cita_programada_paciente;
    private java.util.List<InterfazCita.Citaentidad> citaentidadList;
    private javax.persistence.Query citaentidadQuery;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelCreacionCitaExterna;
    private javax.swing.JTabbedPane panelCreacionCitaProgramada;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
