/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazPaciente;
import PacientesJpa.PacienteJpaController;
import PacientesJpa.PacienteObjeto;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author Mr josh
 */
public class interfazGraficaPaciente extends javax.swing.JFrame {

    /**
     * Creates new form interfazGraficaPaciente
     */
    public interfazGraficaPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 40, 30));

        jLabel8.setText("Seleccione el id del paciente a modificar");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jButton3.setText("editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 600, 110));

        jButton4.setText("Descartar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        jButton5.setText("Guardar cambios");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        jTabbedPane1.addTab("Editar", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 540, 420));

        jButton2.setText("Obtener pacientes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 140, 40));

        jTabbedPane1.addTab("Control", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 80, 30));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, 30));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 80, 30));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 80, 30));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 100, 30));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 94, 100, 30));

        jLabel1.setText("Ocupacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel2.setText("Ingreso de datos del nuevo paciente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel4.setText("Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel5.setText("Edad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, 20));

        jLabel6.setText("Direccion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jLabel7.setText("Religion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, 30));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 440, 30));

        jTabbedPane1.addTab("Creacion", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ClinicasADPU");
        PacienteJpaController pc = new PacienteJpaController(emf);
        int NumeroPacientes = pc.getPacienteCount();
        int contwhile=0;
        pc.NombresDePacientes();
        pc.ApellidosDePacientes();
        pc.DireccionesDePacientes();
        pc.EdadesDePacientes();
        pc.OcupacionesDePacientes();
        pc.ReligionesDePacientes();

        DefaultTableModel dtm = new DefaultTableModel();
        JTable tabla = this.jTable1;
        tabla.setModel(dtm);
        dtm.setColumnIdentifiers(new Object[]{"ID","APELLIDO","NOMBRE","EDAD","DIRECCION","OCUPACION","RELIGION"});
        try {
            while(contwhile <= NumeroPacientes){
                dtm.addRow(new Object[]{contwhile+1,
                    pc.ApellidosDePacientes().get(contwhile),
                    pc.NombresDePacientes().get(contwhile),
                    pc.EdadesDePacientes().get(contwhile),
                    pc.DireccionesDePacientes().get(contwhile),
                    pc.OcupacionesDePacientes().get(contwhile),
                    pc.ReligionesDePacientes().get(contwhile)});
            contwhile++;
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Boton de agregar, este boton agrega el paciente a la base de datos.
        String nombre;
        String apellido;
        int edad;
        String direccion;
        String religion;
        String ocupacion;

        nombre=(String)jTextField1.getText();
        apellido=(String)jTextField2.getText();
        edad = Integer.parseInt(jTextField3.getText());
        direccion=(String)jTextField4.getText();
        religion=(String)jTextField5.getText();
        ocupacion=(String)jTextField6.getText();
        //accion de insertar datos en la base de datos.
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ClinicasADPU");
        PacienteObjeto nuevoPaciente = new PacienteObjeto();
        PacienteJpaController pc = new PacienteJpaController(emf);

        long ultimo = pc.getPacienteCount();
        System.out.println(ultimo);
        nuevoPaciente.setId(ultimo + 1 );
        nuevoPaciente.setNombre(nombre);
        nuevoPaciente.setApellido(apellido);
        nuevoPaciente.setEdad(edad);
        nuevoPaciente.setDireccion(direccion);
        nuevoPaciente.setReligion(religion);
        nuevoPaciente.setOcupacion(ocupacion);

        pc.create(nuevoPaciente);
        jTextField1.setText(" ");
        jTextField2.setText(" ");
        jTextField3.setText(" ");
        jTextField4.setText(" ");
        jTextField5.setText(" ");
        jTextField6.setText(" ");
        System.out.println(pc.getPacienteCount());
        JOptionPane.showMessageDialog(null, "Paciente ingresado correctamente");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jTextField7.getText());
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ClinicasADPU");
        PacienteJpaController pc = new PacienteJpaController(emf);
        DefaultTableModel dtm = new DefaultTableModel();
        JTable tabla = this.jTable3;
        tabla.setModel(dtm);
        dtm.setColumnIdentifiers(new Object[]{"ID","APELLIDO","NOMBRE","EDAD","DIRECCION","OCUPACION","RELIGION"});
        System.out.println((String)pc.TraerPaciente(id).get(1) +" "+(String)pc.TraerPaciente(id).get(2));
        try {
            pc.TraerPaciente(id);
               dtm.addRow(new Object[]{id,pc.TraerPaciente(id).get(0),
               pc.TraerPaciente(id).get(1),
               pc.TraerPaciente(id).get(2),
               pc.TraerPaciente(id).get(3),
               pc.TraerPaciente(id).get(4),
               pc.TraerPaciente(id).get(5)
               });
           
            
        } catch (Exception e) {
        }
        jButton3.setEnabled(false);
        jTextField7.setEnabled(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void recarga(){
        DefaultTableModel dtm = new DefaultTableModel();
        JTable tablapaciente = this.jTable3;
        JTable tablapacientes = this.jTable1;
        tablapaciente.setModel(dtm);
        tablapacientes.setModel(dtm);
        dtm.setColumnIdentifiers(new Object[]{"ID","APELLIDO","NOMBRE","EDAD","DIRECCION","OCUPACION","RELIGION"});
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ClinicasADPU");
        PacienteJpaController pc = new PacienteJpaController(emf);
        PacienteObjeto PacienteAEditar = new PacienteObjeto();
        
        
         int id = (int) this.jTable3.getValueAt(0, 0);
        String nuevoapellido= (String) this.jTable3.getValueAt(0, 1);
        String nuevonombre = (String) this.jTable3.getValueAt(0, 2);
        String nuevaedad = (String) this.jTable3.getValueAt(0, 3);
        String nuevadireccion= (String) this.jTable3.getValueAt(0, 4);
        String nuevaocupacion = (String) this.jTable3.getValueAt(0, 5);
        String nuevareligion =  (String) this.jTable3.getValueAt(0, 6);

        System.out.println(id);
        System.out.println(nuevoapellido);
        System.out.println(nuevonombre);
        System.out.println(nuevaedad);
        System.out.println(nuevadireccion);
        System.out.println(nuevaocupacion);
        System.out.println(nuevareligion);
        
        pc.EditarPaciente(id, nuevoapellido, nuevonombre, nuevaedad, nuevadireccion, nuevaocupacion, nuevareligion);
        
        JOptionPane.showMessageDialog(null, "edicion del paciente exitosa");
              jButton3.setEnabled(true);
        jTextField7.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         int id = Integer.parseInt(jTextField7.getText());
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ClinicasADPU");
        PacienteJpaController pc = new PacienteJpaController(emf);
        DefaultTableModel dtm = new DefaultTableModel();
        JTable tabla = this.jTable3;
        tabla.setModel(dtm);
        dtm.setColumnIdentifiers(new Object[]{"ID","APELLIDO","NOMBRE","EDAD","DIRECCION","OCUPACION","RELIGION"});
        System.out.println((String)pc.TraerPaciente(id).get(1) +" "+(String)pc.TraerPaciente(id).get(2));
        try {
            pc.TraerPaciente(id);
               dtm.addRow(new Object[]{id,pc.TraerPaciente(id).get(0),
               pc.TraerPaciente(id).get(1),
               pc.TraerPaciente(id).get(2),
               pc.TraerPaciente(id).get(3),
               pc.TraerPaciente(id).get(4),
               pc.TraerPaciente(id).get(5)
               });
           
            
        } catch (Exception e) {
        }
               jButton3.setEnabled(true);
        jTextField7.setEnabled(true);
        JOptionPane.showMessageDialog(null, "CAMBIOS DESCARTADOS.");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazGraficaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazGraficaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazGraficaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazGraficaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new interfazGraficaPaciente().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
